name: MushroomIslandSpread
main: me.nathanaelps.plugins.mushroomislandspread.MushroomIslandSpread
author: nathanaelps
version: b.02
commands:
  mushload:
    description: Reload Config
    usage: /mushload